export const INITIAL_TRIPS = [
  {
    id: 1,
    tripName: "Summer Beach Escape",
    destination: "Bali, Indonesia",
    startDate: "2026-06-15",
    endDate: "2026-06-25",
    category: "Beach",
    budget: "2000",
    spent: "1450",
    collaborators: "Sarah Johnson, Emily Davis",
    packingList: "swimsuit, pyjama, sunglasses, t-shirts, charger",
  },
  {
    id: 2,
    tripName: "Alpine Adventure",
    destination: "Swiss Alps, Switzerland",
    startDate: "2026-08-17",
    endDate: "2026-08-24",
    category: "Mountain",
    budget: "3500",
    spent: "3600",
    collaborators: "Frank Reynolds",
    packingList: "hiking boots, jacket, gloves, thermos, map",
  },
  {
    id: 3,
    tripName: "City Break Paris",
    destination: "Paris, France",
    startDate: "2026-09-01",
    endDate: "2026-09-07",
    category: "City",
    budget: "1800",
    spent: "900",
    collaborators: "",
    packingList: "passport, camera, comfortable shoes, umbrella",
  },
  {
    id: 4,
    tripName: "Road Trip Italy",
    destination: "Tuscany, Italy",
    startDate: "2026-05-10",
    endDate: "2026-05-18",
    category: "Road Trip",
    budget: "2200",
    spent: "1200",
    collaborators: "Alex Popescu",
    packingList: "car charger, sunglasses, map, snacks, camera",
  },
  {
    id: 5,
    tripName: "Cultural Tokyo Tour",
    destination: "Tokyo, Japan",
    startDate: "2026-10-05",
    endDate: "2026-10-15",
    category: "Cultural",
    budget: "3000",
    spent: "1800",
    collaborators: "Maria Ionescu",
    packingList: "passport, adapter, camera, comfortable shoes",
  },
  {
    id: 6,
    tripName: "Desert Adventure",
    destination: "Dubai, UAE",
    startDate: "2026-11-12",
    endDate: "2026-11-20",
    category: "Adventure",
    budget: "2500",
    spent: "950",
    collaborators: "",
    packingList: "sunscreen, hat, light clothes, water bottle",
  },
  {
    id: 7,
    tripName: "Weekend in Prague",
    destination: "Prague, Czech Republic",
    startDate: "2026-04-02",
    endDate: "2026-04-06",
    category: "City",
    budget: "900",
    spent: "350",
    collaborators: "Andrei Georgescu",
    packingList: "jacket, passport, camera, cash",
  },
];

export const CATEGORIES = [
  "Beach",
  "Mountain",
  "City",
  "Adventure",
  "Cultural",
  "Road Trip",
  "Other",
];

export const PAGE_SIZE = 5;

export const emptyForm = () => ({
  tripName: "",
  destination: "",
  startDate: "",
  endDate: "",
  category: "",
  budget: "",
  spent: "",
  collaborators: "",
  packingList: "",
});